displayName: LoadTest-CICD-Pipeline
testPlan: HTTP Request.jmx
description: Test the Running Log Logic App
engineInstances: 2
testId: 8f74f731-3634-433e-8581-3219fc2ad4ef
splitAllCSVs: True
configurationFiles:
- RunningData.csv
failureCriteria:
- p90(response_time_ms) > 300
- percentage(error) > 50
secrets:
- name: password
  value: https://kv-load-test03.vault.azure.net/secrets/password
autoStop:
  errorPercentage: 90
  timeWindow: 60
