name: Bicep_Resource_Build

on: 
    workflow_dispatch:
    
    workflow_call:
env:
    bicepfilePath: ./Bicep-Template/main-deploy.bicep

jobs:
    # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3

        # Builds the Bicep template
        - name: bicep-build-output
          uses: Azure/bicep-build-action@v1.0.1
          with:
              bicepFilePath: ${{  env.bicepfilePath }}              
              outputFilePath: ./main-deploy.json
        
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v3.1.1
          with:
            path: ./main-deploy.json

    deploy:
        runs-on: ubuntu-latest
        environment : {
              name: 'development'
        }
        needs: [build]
        steps:
        - uses: actions/checkout@v3

        - name: Azure Login
          uses: Azure/login@v1.4.3
          with:
            creds: ${{ secrets.AZURE_SP }}
        
        - name: what-if deploy
          uses: azure/arm-deploy@v1
          
          with:
            scope: subscription
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
            template: ./bicep-template/main-deploy.bicep
            parameters: ./bicep-template/parameters.json servicePrincipalId=${{ secrets.SERVICE_PRINCIPAL_ID }}
            # additionalArguments: "--what-if"
            region: eastus2

