name: Main-Workflow

on: 
    workflow_dispatch

jobs:

    deploy-resources:
        uses: ./.github/workflows/CreateResource.yml
        secrets: inherit
    
    deploy-run-load-test:
        needs: deploy-resources
        uses: ./.github/workflows/CD.yml
        secrets: inherit
        